-- MySQL Script generated by MySQL Workbench
-- Mon Feb 13 22:07:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senai_exercicios_segunda_lista
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senai_exercicios_segunda_lista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senai_exercicios_segunda_lista` DEFAULT CHARACTER SET utf8 ;
USE `senai_exercicios_segunda_lista` ;

-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`pessoa_fisica` (
  `idpessoa_fisica` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `rg` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`idpessoa_fisica`),
  INDEX `fk_pessoa_fisica_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_pessoa_fisica_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`pessoa_juridica` (
  `idpessoa_juridica` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `inscricao_estadual` VARCHAR(255) NULL,
  PRIMARY KEY (`idpessoa_juridica`),
  INDEX `fk_pessoa_juridica_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_pessoa_juridica_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `numero_telefone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtelefone`),
  INDEX `fk_telefone_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`email` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `endereco_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idemail`),
  INDEX `fk_email_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`cidade` (
  `idcidade` INT NOT NULL AUTO_INCREMENT,
  `idestado` INT NOT NULL,
  `nome_cidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado1_idx` (`idestado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `senai_exercicios_segunda_lista`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`bairro` (
  `idbairro` INT NOT NULL AUTO_INCREMENT,
  `idcidade` INT NOT NULL,
  `nome_bairro` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idbairro`),
  INDEX `fk_bairro_cidade1_idx` (`idcidade` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `senai_exercicios_segunda_lista`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idbairro` INT NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero_endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_cliente1_idx` (`idcliente` ASC),
  INDEX `fk_endereco_bairro1_idx` (`idbairro` ASC),
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`idbairro`)
    REFERENCES `senai_exercicios_segunda_lista`.`bairro` (`idbairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descricao_produto` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `data_pedido` DATE NOT NULL,
  `total_pedido` FLOAT NOT NULL,
  `total_itens` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`produto_pedido` (
  `idproduto_pedido` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NOT NULL,
  `idpedido` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_produto_pedido` FLOAT NOT NULL,
  PRIMARY KEY (`idproduto_pedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`idpedido` ASC),
  INDEX `fk_produto_has_pedido_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `senai_exercicios_segunda_lista`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `senai_exercicios_segunda_lista`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `idpedido` INT NOT NULL,
  `data_venda` DATE NOT NULL,
  `valor_venda` FLOAT NOT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `fk_venda_pedido1_idx` (`idpedido` ASC),
  CONSTRAINT `fk_venda_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `senai_exercicios_segunda_lista`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`conta_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`conta_receber` (
  `idconta_receber` INT NOT NULL AUTO_INCREMENT,
  `idvenda` INT NOT NULL,
  `valor_conta_receber` FLOAT NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idconta_receber`),
  INDEX `fk_conta_receber_venda1_idx` (`idvenda` ASC),
  CONSTRAINT `fk_conta_receber_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `senai_exercicios_segunda_lista`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`nota_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`nota_fiscal` (
  `idnota_fiscal` INT NOT NULL AUTO_INCREMENT,
  `idvenda` INT NOT NULL,
  `numero_nota_fiscal` INT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_saida` DATE NOT NULL,
  `valor_nota_fical` FLOAT NOT NULL,
  `total_impostos` FLOAT NOT NULL,
  PRIMARY KEY (`idnota_fiscal`),
  INDEX `fk_nota_fiscal_venda1_idx` (`idvenda` ASC),
  CONSTRAINT `fk_nota_fiscal_venda1`
    FOREIGN KEY (`idvenda`)
    REFERENCES `senai_exercicios_segunda_lista`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`crm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`crm` (
  `idcrm` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `texto_crm` TEXT NOT NULL,
  `data_crm` DATE NOT NULL,
  PRIMARY KEY (`idcrm`),
  INDEX `fk_crm_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_crm_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `senai_exercicios_segunda_lista`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senai_exercicios_segunda_lista`.`estoque_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senai_exercicios_segunda_lista`.`estoque_produto` (
  `idestoque_produto` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NULL,
  `quantidade_estoque` INT NULL,
  PRIMARY KEY (`idestoque_produto`),
  INDEX `fk_estoque_produto_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_estoque_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `senai_exercicios_segunda_lista`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
